---
title: "Draft Deliverables"
author: "Karen Detter"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(naniar)
library(sf)

#load data

data <- read_csv("data/IPEDS_data.csv")
names(data)
```

```{r}
#Deliverable 1 - univariate plot of categorical variable
#Barplot of enrollment size category 

#Set "Not reported" value to NA
data %>% replace_with_na(replace = list(Size = "Not reported"))

#factor Size variable and order category values
data$Size = factor(data$Size, levels = c("Under 1,000", "1,000 - 4,999", "5,000 - 9,999", "10,000 - 19,999", "20,000 and above"), ordered = TRUE)

#Create chart
sizechart=ggplot(data=subset(data, !is.na(Size)), aes(x=Size)) +
  geom_bar() +
  labs(title = "Institution Size By Enrollment") +
  labs(subtitle = "Most Institutions in the Sample Had Smaller Populations") +
  labs(x= "Total Enrollment", y = "Number of Institutions")
sizechart

#Save chart 'size'

saveRDS(sizechart, file = "sizechart.rds")

```



```{r}
#Deliverable 2 - univariate plot of numeric variable
#Histogram of on-time graduation rate

base = ggplot(data=data)
ontimechart= base + geom_histogram(aes(x=`Graduation rate - Bachelor degree within 4 years, total`)) +
    labs(title = "Distribution of On-Time Graduation Rates") +
  labs(subtitle = "A Mean of Only 41% of Students Completed Bachelor's Degrees in 4 Years") +
  labs(x= "% of Graduates Who Finished in Four Years", y = "Number of Institutions")
ontimechart

#Save chart 'ontime'

saveRDS(ontimechart, file = "ontimechart.rds")

```

```{r}
#Deliverable 3 - bivariate plot of size and 4-year graduation rates

bysizechart= base + geom_boxplot(data=subset(data, !is.na(Size)), aes(x= Size, y=`Graduation rate - Bachelor degree within 4 years, total`)) +
  labs(title = "On-Time Graduation Rates By Institution Size") +
  labs(subtitle = "Low 4-Year Graduation Rates Are Common Regardless of School Size") +
  labs(x= "Total Enrollment", y = "% of Graduates Who Finished in 4 Years")
bysizechart

#Save chart 'bysize'

saveRDS(bysizechart, file = "bysizechart.rds")

```

```{r}
#Deliverable 4 - choropleth map: Concentration of Surveyed Institutions by State

#import spatial data
shape_data <- st_read("data/s_08mr23.shp")

```

```{r}
#standardize identifier in both data sets to 'State'

shape_data <- shape_data %>% 
  rename(State = NAME)
```

```{r}
#merge data sets

merged_data <- left_join(shape_data,data, by = "State")
```

```{r}
#create map

map <- ggplot(merged_data) +
  geom_sf(aes(fill = `Graduation rate - Bachelor degree within 4 years, total`), color = "white", size = 2.0) +
  scale_fill_viridis_c() +
  theme_minimal() +
  labs(fill = "% of Graduates Finishing in 4 Years", title = "Level of 4-Year Graduation By State")
map
```

```{r}

```

